# Generated by Django 3.1.6 on 2021-02-15 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upvote',
            field=models.ManyToManyField(blank=True, through='api.Upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
