version: '3.7'
services:
  web:
    build: .
    command: python blog/manage.py makemigrations
    command: python blog/manage.py migrate
    command: python blog/python manage.py migrate sessions
    command: python blog/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres